### ISSUE TITLE
Capacitación web

### ISSUE THREAD

**Issue by joacoZubiria** [pdepviernestm/2023-bienvenida-luladelucas#1]
Hola Lourdes, muy interesante tu presentación, me gustaría saber donde te capacitaste y en que tecnologías. 
Saludosss

**Comment by luladelucas** [comment]
Hola Joaco! Muchas gracias :) 
Me capacité en el Centro de e-Learning UTN! En HTML, CSS, JS, Node Js y MySQL (aunque esta ya sabía por el laburo)
